### ISSUE TITLE
Unsupported multi stage build

### ISSUE THREAD

**Issue by giannisalinetti** [prometherion/openshift-prometheus-grafana-ambassador#3]
When trying to build the Dockerfile from a version of Docker prior to 17.06 the build fails with the message: 

**Error parsing reference: "golang:1.9.4 AS builder" is not a valid repository/tag: invalid reference format**

The issue is related to the unsupported multi-stage build in the used Docker version. Multi stage build is implemented in the Dockerfile to bring the built artifact to a clean scratch based image.

```
Docker version:
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64
 Experimental:    false

```
Docker package:
**docker-1.13.1-44.git584d391.fc27.x86_64**

Operating System:
**Fedora 27**

**Comment by prometherion** [comment]
I will take care to write a backward compatibility Dockerfile for older versions of Docker.
